#! /bin/sh
set -e

if [ -f /usr/lib/libreoffice/program/shell/backing_left.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/shell/backing_left.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/shell/backing_left.png
fi
if [ -f /usr/lib/libreoffice/program/shell/backing_right.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/shell/backing_right.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/shell/backing_right.png
fi
if [ -f /usr/lib/libreoffice/program/shell/backing_rtl_left.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/shell/backing_rtl_left.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/shell/backing_rtl_left.png
fi
if [ -f /usr/lib/libreoffice/program/shell/backing_rtl_right.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/shell/backing_rtl_right.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/shell/backing_rtl_right.png
fi
if [ -f /usr/lib/libreoffice/program/shell/backing_space.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/shell/backing_space.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/shell/backing_space.png
fi
if [ -f /usr/lib/libreoffice/program/intro.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/intro.png
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/intro.png
fi
if [ -f /usr/lib/libreoffice/program/flat_logo.svg.divert ]; then
  rm -f /usr/lib/libreoffice/program/flat_logo.svg
  dpkg-divert --local --remove --rename /usr/lib/libreoffice/program/flat_logo.svg
fi
if [ -f /etc/libreoffice/sofficerc.divert ]; then
  rm -f /etc/libreoffice/sofficerc
  dpkg-divert --local --remove --rename /etc/libreoffice/sofficerc
fi
